# Generated by Django 5.0.2 on 2024-03-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresmodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
