# Generated by Django 5.0.2 on 2024-03-09 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogManager', '0002_alter_featuresmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'feature_types',
                'verbose_name_plural': 'feature_types_table',
            },
        ),
        migrations.RemoveField(
            model_name='featuresmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='featuresmodel',
            name='feature_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogManager.featuretypesmodel'),
        ),
    ]
